### ISSUE TITLE
使用导出的Cookies文件登录，不需要post 登录的信息

### ISSUE THREAD

**Issue by Celthi** [renever/cn_mooc_dl#8]
由于原来的登陆方式失效了，所以选择使用导出的cookies文件来登陆，这样似乎减少了网站修改登录验证时产生的维护，受Coursera-dl启迪。因为只是个人使用为了更好的学习，所以输入用户名和密码模拟发送信息那一块就不写了，不知是否可以提[pull requests](https://github.com/Celthi/cn_mooc_dl).

**Comment by colorfulDragon** [comment]
提示-f参数不存在。你的那个脚本是不是错了。@Celthi

**Comment by Celthi** [comment]
请看看readme file,如果有问题请继续反馈。

**Comment by colorfulDragon** [comment]
我的测试环境跟依赖包都正确，输入的命令也是按照您所要求的“python xuetangx_dl.py  -f cookie.txt "课程链接"”，但是一直都提示
”usage: xuetangx_dl.py [-h] [-u USERNAME] [-p PASSWORD] [--path PATH] [-o]   course_url [course_url ...]
xuetangx_dl.py: error: unrecognized arguments: -f“ ，，如果我没理解错的话，说的应该是xuatangx.py脚本无法识别  -f  参数。如果可以，您能不能在您的机器上测试一下？？谢谢

**Comment by Celthi** [comment]
不好意思，请你重新下载一下[这个](https://github.com/Celthi/cn_mooc_dl)脚本，我漏传了util文件。

**Comment by colorfulDragon** [comment]
谢谢。刚刚重新测试了那个脚本。但是又出现了其他的问题。。。 

E:>python2 F:\Python27\cn_mooc_dl-master\xuetangx_dl.py -f F:\Python27\cn_mooc_
dl-master\cookies.txt "http://www.xuetangx.com/courses/TsinghuaX/TSINGHUA101/_/c
ourseware/b43c2e0d153d4056b4c9682da78669ef/379bfbdda6d84fc3b6e9bc4d59a02673/"
Traceback (most recent call last):
  File "F:\Python27\cn_mooc_dl-master\xuetangx_dl.py", line 210, in <module>
    main()
  File "F:\Python27\cn_mooc_dl-master\xuetangx_dl.py", line 104, in main
    cookies = json.loads(f.read())
  File "F:\Python27\lib\json__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "F:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
不懂是什么情况= =。能解答一下？？谢谢

**Comment by GeekNo** [comment]
@Celthi 大神，遇到跟楼上哪位兄弟一样的问题，怎么解决？？也是“ValueError: No JSON object could be decoded”。操作步骤应该也没错啊，按着教程来的

**Comment by Celthi** [comment]
跟他讨论了一下后，感觉问题是没有正确导出cookies文件。导出的方法是：安装好插件后，按照插件说明的方式在chrome里打开检查元素，即可以看到cookies，然后右键导出cookies。

**Comment by colorfulDragon** [comment]
@GeekNo 已解决。直接用cookie inspector 导出来的那个文件格式跟内容有误。像Celthi说的那样做就得了。@Celthi，3q
